# object.yml
--- 
spring: 
  config.activate.on-profile: object

server: 
  port: 8083

asw.sentence: 
  wordservice: 
#    words: from remote files,from remote files
    words: FROM REMOTE FILES,FROM REMOTE FILES    