# application.yml 
---
# questo e' il profilo di default: 
lucky: 
  word: Default

---
spring: 
  config.activate.on-profile: english 
lucky: 
  word: Happy

---
spring: 
  config.activate.on-profile: italian 
lucky: 
  word: Evviva

